name: apspace_plus
description: A better APSpace

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_session: ^0.1.1
  http: ^0.13.0
  sizer: ^1.1.8
  intl: ^0.17.0
  page_transition: ^1.1.7+6
  hexcolor: ^2.0.3
  graphql_flutter: ^4.0.1
  qr_flutter: ^4.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: OCR
      fonts:
        - asset: lib/fonts/ocra/OCR-A Regular.ttf
          weight: 400
    - family: OpenSans
      fonts:
        - asset: lib/fonts/OpenSans/OpenSans-Light.ttf
        - asset: lib/fonts/OpenSans/OpenSans-Regular.ttf
        - asset: lib/fonts/OpenSans/OpenSans-SemiBold.ttf
        - asset: lib/fonts/OpenSans/OpenSans-Bold.ttf
        - asset: lib/fonts/OpenSans/OpenSans-ExtraBold.ttf
    - family: Montserrat
      fonts:
        - asset: lib/fonts/Montserrat/Montserrat-Thin.ttf
        - asset: lib/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: lib/fonts/Montserrat/Montserrat-Light.ttf
        - asset: lib/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: lib/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: lib/fonts/Montserrat/Montserrat-Semibold.ttf
        - asset: lib/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: lib/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: lib/fonts/Montserrat/Montserrat-Black.ttf
    - family: Quicksand
      fonts:
        - asset: lib/fonts/Quicksand/Quicksand-Light.ttf
        - asset: lib/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: lib/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: lib/fonts/Quicksand/Quicksand-Semibold.ttf
        - asset: lib/fonts/Quicksand/Quicksand-Bold.ttf

  assets:
    - lib/images/


  #100: Thin, Hairline, Ultra-light, Extra-light
  #200: Light
  #300: Book
  #400: Regular, Normal, Plain, Roman, Standard
  #500: Medium
  #600: Semi-bold, Demi-bold
  #700: Bold
  #800: Heavy, Black, Extra-bold
  #900: Ultra-black, Extra-black, Ultra-bold, Heavy-black, Fat, Poster

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
